### Output : The person left (Exited) the bank or not

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
## Load the dataset
df=pd.read_csv("Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [4]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

## Encode Categorical Variables

In [5]:
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [6]:
df['Gender'].unique()

array([0, 1])

In [7]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

## One Hot Encode Geography column

In [8]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder(sparse_output=False)
geo_encoder=onehot_encoder_geo.fit_transform(df[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [9]:
geo_column_names=onehot_encoder_geo.get_feature_names_out(['Geography'])
geo_column_names

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [10]:
geo_encoded_df=pd.DataFrame(data=geo_encoder,columns=geo_column_names)

In [11]:
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

## Combine the oneHotEncoded columns with original dataframe

In [12]:
df=pd.concat([df.drop(columns='Geography',axis=1),geo_encoded_df],axis=1)

In [13]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

## Save the Encoder and Scaler

In [14]:
with open("classification_label_encoder_gender.pkl",'wb') as file:
    pickle.dump(label_encoder_gender,file)

with open("classification_onehot_encoder_geo.pkl","wb") as file:
    pickle.dump(onehot_encoder_geo,file) 


## Divide the data into independent and dependent

In [15]:
X=df.drop("Exited",axis=1)
y=df['Exited']

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Standard Scaler

In [17]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [19]:
with open ("classification_scaler.pkl",'wb') as file:
    pickle.dump(scaler,file)

### ANN Implementation

In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime


### Build Our ANN model

In [21]:
X_train.shape,X_train.shape[1]

((8000, 12), 12)

In [22]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), #HL1 Connected with input layer
    Dense(32,activation='relu'), # HL2
    Dense(1,activation="sigmoid") #output layer
])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                832       
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Compile the Model

In [24]:
# opt = optimizers
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()

In [25]:
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

### Setup the TensorBoard

In [26]:
log_dir="logs/fit/"+datetime.datetime.now().strftime("%Y-%m-%d__%H-%M-%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)
# histogram_freq=1 tells the TensorBoard callback to perform this action at the end of every single epoch.

### Setup Early Stopping

In [27]:
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

### Training the Model

In [28]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100


250/250 [==============================] - 2s 3ms/step - loss: 0.3951 - accuracy: 0.8325 - val_loss: 0.3551 - val_accuracy: 0.8490
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3576 - accuracy: 0.8533 - val_loss: 0.3579 - val_accuracy: 0.8565
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3491 - accuracy: 0.8571 - val_loss: 0.3546 - val_accuracy: 0.8585
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3427 - accuracy: 0.8596 - val_loss: 0.3501 - val_accuracy: 0.8605
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3389 - accuracy: 0.8606 - val_loss: 0.3483 - val_accuracy: 0.8580
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3373 - accuracy: 0.8611 - val_loss: 0.3553 - val_accuracy: 0.8520
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3366 - accuracy: 0.8634 - val_loss: 0.3407 - val_accuracy: 0.86

In [29]:
model.save("classification_model.h5")

c:\PYTHON\Python_Udemy\Projects\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


### Load TensorBoard Extension

In [30]:
%load_ext tensorboard

In [31]:
%tensorboard --logdir logs/fit/

Reusing TensorBoard on port 6006 (pid 3412), started 1 day, 13:08:33 ago. (Use '!kill 3412' to kill it.)

### Load the Pickel File